apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  labels:
    app: nginx-app
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/DevUnnati/gitops-1.git
    targetRevision: main
    path: overlay/prod-cluster/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  
